### PR TITLE
Add option for minified files to overwrite existing ones

### PR DESCRIPTION
**Pull request by nizarmah**
As requested in #15 this pull request adds a new optional parameter to allow members to overwrite existing files with the minified versions of these files.

### CODE REVIEW

**Comment by nizarmah** [comment]
@ronan-smith @dbjpanda since you both were advocates of the overwrite option, would anyone of you like to provide a review on this pull request? Let me know please, I'll give you a chance in case you want to participate 😃 

Otherwise, I'll merge this by Wednesday August 18 👍🏼

**Review by ronan-smith — COMMENTED** [review]
Hi @nizarmah, thank you for giving me chance to review this - I applaud your drive to improve your project. While I have absolutely no experience writing GitHub actions I think I have spotted something... **In your README.md example have you forgotten to add the Overwrite parameters as they default to false? There's no "with:" statment.**

**Comment by nizarmah** [comment]
@ronan-smith my pleasure 😃 I'm glad you had the chance to review. The goal behind this is either for me to learn something new or for the reviewer. 

> In your README.md example have you forgotten to add the Overwrite parameters as they default to false? There's no "with:" statment.

Nice eye! I updated that in the latest commit 👍🏼 

I'll wait for your approval to merge! 🚀

**Review by ronan-smith — APPROVED** [review]
Everything looks good to me, thanks for adding this feature so fast! 😃

**Comment by nizarmah** [comment]
> thanks for adding this feature so fast!

Least I can do after being unresponsive on the opened issue! Sorry about that! 

> If you hadn't noticed already, this is my first GitHub interaction on a repo other than my own

I have! haha! 

I hope more interactions with other repos are yet to come 😃 

Your opened issue is now a great addition to this action, so don't hesitate to open issues and pull requests on repos even if you aren't confident or sure of what you're doing. You've got this 💪🏼

**Pull request merged**
