### PR TITLE
Update action version number in README.md

### PR DESCRIPTION
**Pull request by ronan-smith**
On attempting to use this action it failed with the error `Unable to resolve action nizarmah/auto-minify@v2, unable to find version v2` - after checking the repository it looks like the examples have not been updated to match the release number.

### CODE REVIEW

**Comment by ronan-smith** [comment]
Hi @nizarmah - After you implemented #15 I tried to run the action in my personal workflow and it failed even though I was following your documentation.

I realised what I needed to do in order to make the action work again, I have updated the examples in the README.md to reflect this.

Please let me know if this isn't suitable! 😄

**Comment by nizarmah** [comment]
Hello @ronan-smith! Thanks for opening this pull request!

To be honest, I'm not really sure yet how to deal with Semantic Versioning and Documentations.

So I was planning to look into things more closely over the weekend to have a better idea if this change is needed, or if I should do a small trick with the tagging.

I'll let you know. I'll either have this merged by Monday, or I'll solve the issue in another way 👍🏼 

I'll keep you updated over this pull request 😃

**Comment by ronan-smith** [comment]
Thanks for taking the time to respond @nizarmah 😃 Please keep me informed, at the moment if people use the examples in the README then their action will fail, it either needs to be v2.0 or v2.1 - _not sure if you can edit releases once pushed but if you change the versioning system again then the workflows using the action will error as mine did._

**Comment by nizarmah** [comment]
@ronan-smith you're right. The current version is problematic. Accordingly, I'm thinking of merging the changes, and then looking into the semantic versioning over the weekend and making the necessary changes. 👍🏼 

Thanks again for your contribution 🤗

**Comment by Spreeuw** [comment]
@nizarmah Here's what the manual says about [versioning](
https://github.com/actions/toolkit/blob/master/docs/action-versioning.md#recommendations):

You're already following semantic versioning so I think all that was missing is step 3?

> 3. **Make the new release available to those binding to the major version tag:** Move the major version tag (v1, v2, etc.) to point to the ref of the current release. This will act as the stable release for that major version. You should keep this tag updated to the most recent stable minor/patch release.
>
> ```
> git tag -fa v1 -m "Update v1 tag"
> git push origin v1 --force
> ```

So rather than changing the readme for each release, if you stick to SemVer you can leave `@v2` in the examples, and all you need to do is update the main `v2` tag after each release. I you could automate this pretty easily I think ;)

yep, just 2 random examples:

https://github.com/marketplace/actions/actions-tagger
https://github.com/marketplace/actions/update-semver

**Pull request merged**
